DROP DATABASE IF EXISTS `petstore`;
CREATE DATABASE `PETSHOP` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `PETSHOP`;

SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET time_zone = '+00:00';
START TRANSACTION;

CREATE TABLE `CUA_HANG` (
    `MACUAHANG` INT NOT NULL AUTO_INCREMENT,
    `TENCUAHANG` NVARCHAR(255) NOT NULL,
    `DIACHI` NVARCHAR(255),
    `SODIENTHOAI` NVARCHAR(255),
    `EMAIL` NVARCHAR(255),
    `TRANGTHAI` BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (`MACUAHANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `SAN_PHAM` (
    `MASANPHAM` INT NOT NULL AUTO_INCREMENT,
    `TENSANPHAM` VARCHAR(255) NOT NULL,
    `DONVITINH` NVARCHAR(255) NOT NULL,
    `GIANIEMYET` BIGINT NOT NULL,
    `THUE` FLOAT NOT NULL,
    `MAVACH` NVARCHAR(255) NOT NULL,
    `COTHEMUA` BOOLEAN NOT NULL COMMENT 'True cho Thức ăn, Phụ kiện, Thú cưng; False cho Dịch vụ',
    `COTHEBAN` BOOLEAN NOT NULL COMMENT 'True cho mọi thứ khách có thể trả tiền; False cho vật tư tiêu hao nội bộ',
    `POS` BOOLEAN NOT NULL COMMENT 'True cho những sản phẩm có thể bán; False cho những thứ không thế bán',
    `THUONGHIEU` NVARCHAR(255) NOT NULL,
    `XUATXU` NVARCHAR(255) NOT NULL,
    `PHUHOP` NVARCHAR(255) NOT NULL,
    `THANHPHAN` TEXT NOT NULL,
    `HUONGDAN` TEXT NOT NULL,
    `MOTA` TEXT NOT NULL,
    PRIMARY KEY (`MASANPHAM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `DOI_TAC` (
    `MADOITAC` INT NOT NULL AUTO_INCREMENT,
    `TENDOITAC` NVARCHAR(255) NOT NULL,
    `SODIENTHOAI` NVARCHAR(255),
    `DIACHI` NVARCHAR(255),
    `EMAIL` NVARCHAR(255),
    `LOAIDOITAC` NVARCHAR(255) COMMENT 'KHACH_HANG / NHA_CUNG_CAP / CA_HAI',
    PRIMARY KEY (`MADOITAC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `KHACH_HANG` (
    `MADOITAC` INT NOT NULL,
    `DIEMTICHLUY` INT NOT NULL DEFAULT 0 COMMENT 'Cộng điểm dựa trên hóa đơn',
    `NGAYTHAMGIA` DATE NOT NULL,
    `LOAIKHACHHANG` NVARCHAR(255) NOT NULL DEFAULT 'Đồng' COMMENT 'Đồng/Bạc/Vàng',
    PRIMARY KEY (`MADOITAC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `NHA_CUNG_CAP` (
    `MADOITAC` INT NOT NULL,
    `MASOTHUE` NVARCHAR(255) NOT NULL,
    `DIEUKHOANTHANHTOAN` NVARCHAR(255) NOT NULL,
    `GHICHU` NVARCHAR(255) NOT NULL,
    PRIMARY KEY (`MADOITAC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `VAI_TRO` (
    `MAVAITRO` INT NOT NULL AUTO_INCREMENT,
    `TENVAITRO` NVARCHAR(255) NOT NULL,
    `QUYENHAN` JSON NOT NULL,
    PRIMARY KEY (`MAVAITRO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `NHAN_VIEN` (
    `MANHANVIEN` INT NOT NULL AUTO_INCREMENT,
    `MACUAHANG` INT,
    `HOTEN` NVARCHAR(255) NOT NULL,
    `SDT` NVARCHAR(255) NOT NULL,
    `EMAIL` NVARCHAR(255) NOT NULL,
    `NGAYVAOLAM` DATE NOT NULL,
    `TRANGTHAI` NVARCHAR(255) NOT NULL COMMENT 'Đang làm việc/ Đã nghỉ việc',
    PRIMARY KEY (`MANHANVIEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PHAN_QUYEN_NHAN_VIEN` (
    `MAVAITRO` INT NOT NULL,
    `MANHANVIEN` INT NOT NULL,
    `NGAYGAN` DATE NOT NULL,
    PRIMARY KEY (`MAVAITRO`, `MANHANVIEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TAI_KHOAN_NHAN_VIEN` (
    `MANHANVIEN` INT NOT NULL,
    `USERNAME` NVARCHAR(255) NOT NULL UNIQUE,
    `PASSWORDHASH` NVARCHAR(255) NOT NULL,
    `PASSWORDHASHHISTORY` NVARCHAR(255) NOT NULL,
    `NGAYTAO` DATE NOT NULL,
    `LAST_LOGIN` DATETIME NULL,
    `TRANG_THAI` BOOLEAN NOT NULL,
    PRIMARY KEY (`MANHANVIEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `HO_SO_LUONG` (
    `MANHANVIEN` INT NOT NULL,
    `MUCLUONG` BIGINT NOT NULL,
    `GIAMTRUBANTHAN` BIGINT NOT NULL DEFAULT 15500000,
    `SONGUOIPHUTHUOC` INT NOT NULL DEFAULT 0,
    `TIENGIAMNPT` BIGINT NOT NULL COMMENT 'SO_NGUOI_PHU_THUOC * 6200000',
    `NGAYCAPNHAP` DATE NOT NULL,
    PRIMARY KEY (`MANHANVIEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PHIEU_LUONG` (
    `MAPHIEU` INT NOT NULL AUTO_INCREMENT,
    `MANHANVIEN` INT NOT NULL,
    `THANGNAM` NVARCHAR(255) NOT NULL,
    `LUONG` BIGINT NOT NULL,
    `TONGBAOHIEMNV` BIGINT NOT NULL COMMENT '10.5%',
    `TONGTHUETNCN` BIGINT NOT NULL,
    `THUCLINH` BIGINT NOT NULL,
    `TRANGTHAI` NVARCHAR(255) NOT NULL COMMENT 'Chưa nhận/Đã nhận',
    PRIMARY KEY (`MAPHIEU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `QUYET_TOAN_THUE_BH` (
    `MAQUYETTOAN` INT NOT NULL AUTO_INCREMENT,
    `MAPHIEU` INT NOT NULL,
    `NGAYQUYETTOAN` DATE NOT NULL,
    `TONGBAOHIEM` BIGINT NOT NULL DEFAULT 0,
    `TONGTHUE` BIGINT NOT NULL DEFAULT 0,
    `GHICHU` NVARCHAR(255),
    PRIMARY KEY (`MAQUYETTOAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHI_TIET_BAO_HIEM` (
    `MACHITIET` INT NOT NULL AUTO_INCREMENT,
    `MAPHIEU` INT NOT NULL,
    `LOAIBAOHIEM` NVARCHAR(255) NOT NULL,
    `TYLE` FLOAT NOT NULL,
    `SOTIEN` BIGINT NOT NULL,
    PRIMARY KEY (`MACHITIET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHI_TIET_THUE_TNCN` (
    `MACHITIET` INT NOT NULL AUTO_INCREMENT,
    `MAPHIEU` INT NOT NULL,
    `BAC_THUE` INT NOT NULL,
    `THUNHAPTINHTHUE` BIGINT NOT NULL,
    `THUESUAT` FLOAT NOT NULL,
    `SOTIEN` BIGINT NOT NULL,
    PRIMARY KEY (`MACHITIET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHAM_CONG` (
    `MACHAMCONG` INT NOT NULL AUTO_INCREMENT,
    `MANHANVIEN` INT NOT NULL,
    `NGAY` DATE NOT NULL,
    `GIOVAO` DATETIME NOT NULL,
    `GIORA` DATETIME NOT NULL,
    `SOGIOLAM` FLOAT NOT NULL,
    `TANGCA` FLOAT NOT NULL DEFAULT 0,
    `TRANGTHAI` NVARCHAR(255) NOT NULL,
    `GHICHU` NVARCHAR(255) NOT NULL COMMENT 'Đi muộn, Về sớm, Nghỉ phép, Nghỉ không phép',
    PRIMARY KEY (`MACHAMCONG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `QUAN_LY_PHEP` (
    `IDPHEP` INT NOT NULL AUTO_INCREMENT,
    `MANHANVIEN` INT NOT NULL,
    `NAM` INT NOT NULL,
    `TONGPHEP` INT NOT NULL,
    `DADUNG` INT NOT NULL,
    `CONLAI` INT NOT NULL,
    PRIMARY KEY (`IDPHEP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `DON_XIN_NGHI_PHEP` (
    `MADON` INT NOT NULL AUTO_INCREMENT,
    `MANHANVIEN` INT NOT NULL,
    `LOAINGHI` NVARCHAR(255) NOT NULL COMMENT 'Phép năm, Ốm đau, ...',
    `TUNGAY` DATE NOT NULL,
    `DENNGAY` DATE NOT NULL,
    `SONGAY` INT NOT NULL,
    `LYDO` NVARCHAR(255) NOT NULL,
    `TRANGTHAI` NVARCHAR(255) NOT NULL COMMENT 'Chờ duyệt, Đã duyệt, Từ chối',
    `NGUOIDUYET` INT NULL,
    PRIMARY KEY (`MADON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `DON_HANG` (
    `MADONHANG` INT NOT NULL AUTO_INCREMENT,
    `MACUAHANG` INT NOT NULL,
    `MADOITAC` INT NOT NULL,
    `MANHANVIEN` INT NOT NULL,
    `NGAYTAO` DATETIME NOT NULL,
    `TONGTIENTAMTINH` BIGINT NOT NULL,
    `DIEMMUONDUNG` INT NOT NULL,
    `TRANGTHAI` NVARCHAR(255) NOT NULL COMMENT 'ChoXacNhan, DaXacNhan, Huy',
    `GHICHU` NVARCHAR(255) NOT NULL,
    PRIMARY KEY (`MADONHANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHI_TIET_DON_HANG` (
    `MACHITIET` INT NOT NULL AUTO_INCREMENT,
    `MASANPHAM` INT,
    `MADONHANG` INT,
    `SOLUONG` INT,
    `DONGIA` BIGINT,
    `THANHTIEN` BIGINT,
    PRIMARY KEY (`MACHITIET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `HOA_DON_BAN_HANG` (
    `MAHOADON` INT NOT NULL AUTO_INCREMENT,
    `MADOITAC` INT NOT NULL,
    `MADONHANG` INT NOT NULL,
    `MACUAHANG` INT NOT NULL,
    `NGAYBAN` DATETIME NOT NULL,
    `TONGTIEN` BIGINT NOT NULL,
    `DIEMTICHDUOC` INT NOT NULL,
    `DIEMSUDUNG` INT NOT NULL,
    `PHUONGTHUCTHANHTOAN` NVARCHAR(255) NOT NULL COMMENT 'TIEN_MAT hoặc CHUYEN_KHOAN',
    `MANHANVIEN` INT NOT NULL,
    PRIMARY KEY (`MAHOADON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHI_TIET_HOA_DON_BAN_HANG` (
    `MACHITIET` INT NOT NULL AUTO_INCREMENT,
    `MASANPHAM` INT,
    `MAHOADON` INT,
    `SOLUONG` INT,
    `DONGIA` BIGINT,
    `THANHTIEN` BIGINT,
    PRIMARY KEY (`MACHITIET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `HOA_DON_NHAP_HANG` (
    `MAHOADONNHAP` INT NOT NULL AUTO_INCREMENT,
    `MADOITAC` INT NOT NULL,
    `MANHANVIEN` INT NOT NULL,
    `SOHOADON_VAT` NVARCHAR(255) NOT NULL,
    `NGAYLAP` DATE NOT NULL,
    `TONGTIEN` BIGINT NOT NULL,
    `PHUONGTHUCTHANHTOAN` NVARCHAR(255) NOT NULL,
    `TRANGTHAI_THANHTOAN` NVARCHAR(255) NOT NULL,
    `GHICHU` NVARCHAR(255) NOT NULL,
    PRIMARY KEY (`MAHOADONNHAP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHI_TIET_HOA_DON_NHAP_HANG` (
    `MACHITIET` INT NOT NULL AUTO_INCREMENT,
    `MAHOADONNHAP` INT,
    `MASANPHAM` INT,
    `SOLUONG` INT,
    `SOLUONGDANHAN` INT,
    `DONGIA` BIGINT,
    `THANHTIEN` BIGINT,
    PRIMARY KEY (`MACHITIET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `KHO` (
    `MAKHO` INT NOT NULL AUTO_INCREMENT,
    `MACUAHANG` INT NOT NULL,
    `TENKHO` NVARCHAR(255) NOT NULL,
    `DIACHI` NVARCHAR(255) NOT NULL,
    PRIMARY KEY (`MAKHO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PHIEU_KHO` (
    `SOPHIEU` NVARCHAR(255) NOT NULL,
    `LOAIPHIEU` NVARCHAR(255) NOT NULL COMMENT 'Nhập/ Xuất/ Chuyển',
    `MAHOADON` INT DEFAULT NULL,
    `NGAYLAP` DATE NOT NULL COMMENT 'Ngày lập phiếu',
    `NGAYTHUCPHE` DATE NOT NULL COMMENT 'Ngày xuất/nhập/chuyển hàng trên thực tế',
    `KHODI` INT,
    `KHODEN` INT,
    `DOITAC` INT NOT NULL COMMENT 'Nhà cung cấp nếu là Nhập, Khách hàng nếu là Xuất',
    `TONGGIATRIPHIEU` BIGINT NOT NULL COMMENT 'Dùng trigger để tính',
    `NGUOIPHUTRACH` INT NOT NULL,
    `TRANGTHAI` NVARCHAR(255) NOT NULL COMMENT 'Đang vận chuyển, Đã nhận, Khiếu nại',
    PRIMARY KEY (`SOPHIEU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHI_TIET_PHIEU` (
    `MACHITIET` INT NOT NULL AUTO_INCREMENT,
    `SOPHIEU` NVARCHAR(255) NOT NULL,
    `MASANPHAM` INT NOT NULL,
    `SOLUONG` INT NOT NULL,
    `DONGIA` BIGINT NOT NULL COMMENT 'Nếu là phiếu Nhập: Lưu lịch sử giá. Nếu là phiếu Xuất: Lưu giá vốn tại thời điểm xuất',
    `MALO` NVARCHAR(255),
    `HANSUDUNG` DATE,
    `THANHTIEN` BIGINT NOT NULL COMMENT 'SOLUONG * DONGIA',
    PRIMARY KEY (`MACHITIET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TON_KHO` (
    `MASANPHAM` INT NOT NULL,
    `MAKHO` INT NOT NULL,
    `SOLUONGTON` INT NOT NULL,
    `NGAYCAPNHAP` DATETIME NOT NULL,
    PRIMARY KEY (`MASANPHAM`, `MAKHO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `KIEM_KE` (
    `MAKIEMKE` INT NOT NULL AUTO_INCREMENT,
    `MAKHO` INT NOT NULL,
    `MACUAHANG` INT NOT NULL,
    `NGAYKIEMKE` DATE NOT NULL,
    `NGUOIKIEMKE` INT NOT NULL,
    `TRANGTHAI` NVARCHAR(255) NOT NULL COMMENT 'Đang kiểm / Đã cân đối',
    PRIMARY KEY (`MAKIEMKE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHI_TIET_KIEM_KE` (
    `MACHITIET` INT NOT NULL AUTO_INCREMENT,
    `MAKIEMKE` INT NOT NULL,
    `MASANPHAM` INT NOT NULL,
    `SLHETHONG` INT NOT NULL,
    `SLTHUCTE` INT NOT NULL,
    `SLLECH` INT NOT NULL,
    `LYDOLECH` NVARCHAR(255),
    PRIMARY KEY (`MACHITIET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TAI_KHOAN_NGAN_HANG` (
    `MATAIKHOAN` INT NOT NULL AUTO_INCREMENT,
    `MACUAHANG` INT NOT NULL,
    `TENTAIKHOAN` NVARCHAR(255) NOT NULL,
    `SOTAIKHOAN` NVARCHAR(255) NOT NULL UNIQUE,
    `TENNGANHANG` NVARCHAR(255) NOT NULL,
    `SODU` BIGINT NOT NULL DEFAULT 0,
    `TRANGTHAI` BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (`MATAIKHOAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `LICH_SU_GIAO_DICH_TIEN` (
    `MAGIAODICH` INT NOT NULL AUTO_INCREMENT,
    `MATAIKHOAN` INT NOT NULL,
    `MATAIKHOANDOIUNG` INT NULL,
    `MAHOADONBAN` INT NULL,
    `MAHOADONMUA` INT NULL,
    `MAPHIEULUONG` INT NULL,
    `MAQUYETTOAN` INT NULL,
    `MACUAHANG` INT NOT NULL,
    `NGAYGIAODICH` DATETIME NOT NULL,
    `SOTIEN` BIGINT NOT NULL,
    `LOAIGIAODICH` NVARCHAR(255) NOT NULL,
    `NOIDUNG` NVARCHAR(255),
    PRIMARY KEY (`MAGIAODICH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `QUAN_LY_CHI_NHANH` (
    `MACUAHANG` INT NOT NULL,
    `MANHANVIEN` INT NOT NULL,
    `NGAYBATDAU` DATE NOT NULL,
    `NGAYKETTHUC` DATE NULL,
    PRIMARY KEY (`MACUAHANG`, `MANHANVIEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `DANH_MUC` (
    `MADANHMUC` INT NOT NULL AUTO_INCREMENT,
    `TENDANHMUC` NVARCHAR(255) NOT NULL,
    `MADANHMUCCHA` INT NULL,
    `MOTA` NVARCHAR(255),
    PRIMARY KEY (`MADANHMUC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `SAN_PHAM_DANH_MUC` (
    `MASANPHAM` INT NOT NULL,
    `MADANHMUC` INT NOT NULL,
    PRIMARY KEY (`MASANPHAM`, `MADANHMUC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `KHACH_HANG` ADD CONSTRAINT `FK_KhachHang_DoiTac` FOREIGN KEY (`MADOITAC`) REFERENCES `DOI_TAC` (`MADOITAC`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `NHA_CUNG_CAP` ADD CONSTRAINT `FK_NhaCungCap_DoiTac` FOREIGN KEY (`MADOITAC`) REFERENCES `DOI_TAC` (`MADOITAC`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `NHAN_VIEN` ADD CONSTRAINT `FK_NhanVien_CuaHang` FOREIGN KEY (`MACUAHANG`) REFERENCES `CUA_HANG` (`MACUAHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PHAN_QUYEN_NHAN_VIEN` ADD CONSTRAINT `FK_PhanQuyen_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PHAN_QUYEN_NHAN_VIEN` ADD CONSTRAINT `FK_PhanQuyen_VaiTro` FOREIGN KEY (`MAVAITRO`) REFERENCES `VAI_TRO` (`MAVAITRO`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `TAI_KHOAN_NHAN_VIEN` ADD CONSTRAINT `FK_TaiKhoan_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HO_SO_LUONG` ADD CONSTRAINT `FK_HoSoLuong_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PHIEU_LUONG` ADD CONSTRAINT `FK_PhieuLuong_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `QUYET_TOAN_THUE_BH` ADD CONSTRAINT `FK_QuyetToan_PhieuLuong` FOREIGN KEY (`MAPHIEU`) REFERENCES `PHIEU_LUONG` (`MAPHIEU`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_BAO_HIEM` ADD CONSTRAINT `FK_ChiTietBH_PhieuLuong` FOREIGN KEY (`MAPHIEU`) REFERENCES `PHIEU_LUONG` (`MAPHIEU`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_THUE_TNCN` ADD CONSTRAINT `FK_ChiTietThue_PhieuLuong` FOREIGN KEY (`MAPHIEU`) REFERENCES `PHIEU_LUONG` (`MAPHIEU`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHAM_CONG` ADD CONSTRAINT `FK_ChamCong_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `QUAN_LY_PHEP` ADD CONSTRAINT `FK_QuanLyPhep_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DON_XIN_NGHI_PHEP` ADD CONSTRAINT `FK_NghiPhep_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DON_XIN_NGHI_PHEP` ADD CONSTRAINT `FK_NghiPhep_NguoiDuyet` FOREIGN KEY (`NGUOIDUYET`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `DON_HANG` ADD CONSTRAINT `FK_DonHang_CuaHang` FOREIGN KEY (`MACUAHANG`) REFERENCES `CUA_HANG` (`MACUAHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DON_HANG` ADD CONSTRAINT `FK_DonHang_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DON_HANG` ADD CONSTRAINT `FK_DonHang_KhachHang` FOREIGN KEY (`MADOITAC`) REFERENCES `KHACH_HANG` (`MADOITAC`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_DON_HANG` ADD CONSTRAINT `FK_ChiTietDonHang_SanPham` FOREIGN KEY (`MASANPHAM`) REFERENCES `SAN_PHAM` (`MASANPHAM`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_DON_HANG` ADD CONSTRAINT `FK_ChiTietDonHang_DonHang` FOREIGN KEY (`MADONHANG`) REFERENCES `DON_HANG` (`MADONHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `HOA_DON_BAN_HANG` ADD CONSTRAINT `FK_HoaDonBan_KhachHang` FOREIGN KEY (`MADOITAC`) REFERENCES `KHACH_HANG` (`MADOITAC`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HOA_DON_BAN_HANG` ADD CONSTRAINT `FK_HoaDonBan_DonHang` FOREIGN KEY (`MADONHANG`) REFERENCES `DON_HANG` (`MADONHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HOA_DON_BAN_HANG` ADD CONSTRAINT `FK_HoaDonBan_CuaHang` FOREIGN KEY (`MACUAHANG`) REFERENCES `CUA_HANG` (`MACUAHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HOA_DON_BAN_HANG` ADD CONSTRAINT `FK_HoaDonBan_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_HOA_DON_BAN_HANG` ADD CONSTRAINT `FK_ChiTietHoaDonBan_HoaDonBan` FOREIGN KEY (`MAHOADON`) REFERENCES `HOA_DON_BAN_HANG` (`MAHOADON`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_HOA_DON_BAN_HANG` ADD CONSTRAINT `FK_ChiTietHoaDonBan_SanPham` FOREIGN KEY (`MASANPHAM`) REFERENCES `SAN_PHAM` (`MASANPHAM`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `HOA_DON_NHAP_HANG` ADD CONSTRAINT `FK_HoaDonNhap_NhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HOA_DON_NHAP_HANG` ADD CONSTRAINT `FK_HoaDonNhap_NhaCungCap` FOREIGN KEY (`MADOITAC`) REFERENCES `NHA_CUNG_CAP` (`MADOITAC`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_HOA_DON_NHAP_HANG` ADD CONSTRAINT `FK_ChiTietHoaDonNhap_HoaDonNhap` FOREIGN KEY (`MAHOADONNHAP`) REFERENCES `HOA_DON_NHAP_HANG` (`MAHOADONNHAP`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_HOA_DON_NHAP_HANG` ADD CONSTRAINT `FK_ChiTietHoaDonNhap_SanPham` FOREIGN KEY (`MASANPHAM`) REFERENCES `SAN_PHAM` (`MASANPHAM`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `KHO` ADD CONSTRAINT `FK_Kho_CuaHang` FOREIGN KEY (`MACUAHANG`) REFERENCES `CUA_HANG` (`MACUAHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PHIEU_KHO` ADD CONSTRAINT `FK_PhieuKho_HoaDonNhap` FOREIGN KEY (`MAHOADON`) REFERENCES `HOA_DON_NHAP_HANG` (`MAHOADONNHAP`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PHIEU_KHO` ADD CONSTRAINT `FK_PhieuKho_DoiTac` FOREIGN KEY (`DOITAC`) REFERENCES `NHA_CUNG_CAP` (`MADOITAC`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PHIEU_KHO` ADD CONSTRAINT `FK_PhieuKho_NguoiPhuTrach` FOREIGN KEY (`NGUOIPHUTRACH`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PHIEU_KHO` ADD CONSTRAINT `FK_PhieuKho_KhoDi` FOREIGN KEY (`KHODI`) REFERENCES `KHO` (`MAKHO`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PHIEU_KHO` ADD CONSTRAINT `FK_PhieuKho_KhoDen` FOREIGN KEY (`KHODEN`) REFERENCES `KHO` (`MAKHO`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_PHIEU` ADD CONSTRAINT `FK_ChiTietPhieu_PhieuKho` FOREIGN KEY (`SOPHIEU`) REFERENCES `PHIEU_KHO` (`SOPHIEU`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_PHIEU` ADD CONSTRAINT `FK_ChiTietPhieu_SanPham` FOREIGN KEY (`MASANPHAM`) REFERENCES `SAN_PHAM` (`MASANPHAM`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `TON_KHO` ADD CONSTRAINT `FK_TonKho_SanPham` FOREIGN KEY (`MASANPHAM`) REFERENCES `SAN_PHAM` (`MASANPHAM`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `TON_KHO` ADD CONSTRAINT `FK_TonKho_Kho` FOREIGN KEY (`MAKHO`) REFERENCES `KHO` (`MAKHO`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `KIEM_KE` ADD CONSTRAINT `FK_KiemKe_Kho` FOREIGN KEY (`MAKHO`) REFERENCES `KHO` (`MAKHO`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `KIEM_KE` ADD CONSTRAINT `FK_KiemKe_CuaHang` FOREIGN KEY (`MACUAHANG`) REFERENCES `CUA_HANG` (`MACUAHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `KIEM_KE` ADD CONSTRAINT `FK_KiemKe_NguoiKiemKe` FOREIGN KEY (`NGUOIKIEMKE`) REFERENCES `NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_KIEM_KE` ADD CONSTRAINT `FK_ChiTietKiemKe_KiemKe` FOREIGN KEY (`MAKIEMKE`) REFERENCES `KIEM_KE` (`MAKIEMKE`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CHI_TIET_KIEM_KE` ADD CONSTRAINT `FK_ChiTietKiemKe_SanPham` FOREIGN KEY (`MASANPHAM`) REFERENCES `SAN_PHAM` (`MASANPHAM`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `TAI_KHOAN_NGAN_HANG` ADD CONSTRAINT `FK_TaiKhoanNganHang_CuaHang` FOREIGN KEY (`MACUAHANG`) REFERENCES `CUA_HANG` (`MACUAHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LICH_SU_GIAO_DICH_TIEN` ADD CONSTRAINT `FK_GiaoDich_TaiKhoan` FOREIGN KEY (`MATAIKHOAN`) REFERENCES `TAI_KHOAN_NGAN_HANG` (`MATAIKHOAN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LICH_SU_GIAO_DICH_TIEN` ADD CONSTRAINT `FK_GiaoDich_TaiKhoanDoiUng` FOREIGN KEY (`MATAIKHOANDOIUNG`) REFERENCES `TAI_KHOAN_NGAN_HANG` (`MATAIKHOAN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LICH_SU_GIAO_DICH_TIEN` ADD CONSTRAINT `FK_GiaoDich_HoaDonBan` FOREIGN KEY (`MAHOADONBAN`) REFERENCES `HOA_DON_BAN_HANG` (`MAHOADON`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LICH_SU_GIAO_DICH_TIEN` ADD CONSTRAINT `FK_GiaoDich_HoaDonMua` FOREIGN KEY (`MAHOADONMUA`) REFERENCES `HOA_DON_NHAP_HANG` (`MAHOADONNHAP`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LICH_SU_GIAO_DICH_TIEN` ADD CONSTRAINT `FK_GiaoDich_PhieuLuong` FOREIGN KEY (`MAPHIEULUONG`) REFERENCES `PHIEU_LUONG` (`MAPHIEU`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LICH_SU_GIAO_DICH_TIEN` ADD CONSTRAINT `FK_GiaoDich_QuyetToan` FOREIGN KEY (`MAQUYETTOAN`) REFERENCES `QUYET_TOAN_THUE_BH` (`MAQUYETTOAN`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LICH_SU_GIAO_DICH_TIEN` ADD CONSTRAINT `FK_GiaoDich_CuaHang` FOREIGN KEY (`MACUAHANG`) REFERENCES `CUA_HANG` (`MACUAHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `QUAN_LY_CHI_NHANH` ADD CONSTRAINT `FK_QuanLyChiNhanh_CuaHang` FOREIGN KEY (`MACUAHANG`) REFERENCES `CUA_HANG` (`MACUAHANG`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `QUAN_LY_CHI_NHANH` ADD CONSTRAINT `FK_QuanLyChiNhanh_TaiKhoanNhanVien` FOREIGN KEY (`MANHANVIEN`) REFERENCES `TAI_KHOAN_NHAN_VIEN` (`MANHANVIEN`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `DANH_MUC` ADD CONSTRAINT `FK_DanhMuc_DanhMucCha` FOREIGN KEY (`MADANHMUCCHA`) REFERENCES `DANH_MUC` (`MADANHMUC`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `SAN_PHAM_DANH_MUC` ADD CONSTRAINT `FK_SanPhamDanhMuc_SanPham` FOREIGN KEY (`MASANPHAM`) REFERENCES `SAN_PHAM` (`MASANPHAM`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `SAN_PHAM_DANH_MUC` ADD CONSTRAINT `FK_SanPhamDanhMuc_DanhMuc` FOREIGN KEY (`MADANHMUC`) REFERENCES `DANH_MUC` (`MADANHMUC`) ON UPDATE NO ACTION ON DELETE NO ACTION;

COMMIT;
