USE PETSHOP;

DELIMITER $$

-- ==========================================
-- 1. DROP OLD OBJECTS
-- ==========================================
DROP TRIGGER IF EXISTS TRG_DOITAC_CHECK_KHACHHANG $$
DROP TRIGGER IF EXISTS TRG_DOITAC_CHECK_KHACHHANG_UPDATE $$
DROP TRIGGER IF EXISTS TRG_DOITAC_CHECK_TRUNG_INSERT $$
DROP TRIGGER IF EXISTS TRG_DOITAC_CHECK_TRUNG_UPDATE $$
DROP TRIGGER IF EXISTS TRG_KHACHHANG_RANK_INSERT $$
DROP TRIGGER IF EXISTS TRG_CAPNHAT_LOAI_KHACH $$
DROP TRIGGER IF EXISTS TRG_KHACHHANG_CHAN_XOA $$
DROP TRIGGER IF EXISTS TRG_HOADON_CHECK_DIEM $$
DROP TRIGGER IF EXISTS TRG_HOADON_TICH_DIEM $$
DROP TRIGGER IF EXISTS TRG_HOADON_HOAN_DIEM $$

DROP FUNCTION IF EXISTS FN_KHACH_HANG_TONTAI $$
DROP FUNCTION IF EXISTS FN_SDT_DOI_TAC_TRUNG $$
DROP FUNCTION IF EXISTS FN_EMAIL_DOI_TAC_TRUNG $$

DROP PROCEDURE IF EXISTS SP_THEM_KHACH_HANG $$
DROP PROCEDURE IF EXISTS SP_SUA_KHACH_HANG $$
DROP PROCEDURE IF EXISTS SP_XOA_KHACH_HANG $$
DROP PROCEDURE IF EXISTS SP_LAY_DANH_SACH_KHACH_HANG $$
DROP PROCEDURE IF EXISTS SP_TIM_KIEM_KHACH_HANG $$
DROP PROCEDURE IF EXISTS SP_CAP_NHAT_DIEM_KHACH_HANG $$

-- ==========================================
-- 2. FUNCTIONS
-- ==========================================

CREATE FUNCTION FN_KHACH_HANG_TONTAI(p_MADOITAC INT)
RETURNS BOOLEAN DETERMINISTIC
BEGIN
    RETURN EXISTS(SELECT 1 FROM KHACH_HANG WHERE MADOITAC = p_MADOITAC);
END $$

CREATE FUNCTION FN_SDT_DOI_TAC_TRUNG(p_SODIENTHOAI NVARCHAR(255), p_MADOITAC INT)
RETURNS BOOLEAN DETERMINISTIC
BEGIN
    RETURN EXISTS(SELECT 1 FROM DOI_TAC WHERE SODIENTHOAI = p_SODIENTHOAI AND (p_MADOITAC IS NULL OR MADOITAC <> p_MADOITAC));
END $$

CREATE FUNCTION FN_EMAIL_DOI_TAC_TRUNG(p_EMAIL NVARCHAR(255), p_MADOITAC INT)
RETURNS BOOLEAN DETERMINISTIC
BEGIN
    IF p_EMAIL IS NULL OR TRIM(p_EMAIL) = '' THEN RETURN FALSE; END IF;
    RETURN EXISTS(SELECT 1 FROM DOI_TAC WHERE EMAIL = p_EMAIL AND (p_MADOITAC IS NULL OR MADOITAC <> p_MADOITAC));
END $$

-- ==========================================
-- 3. PROCEDURES
-- ==========================================

-- Thêm khách hàng (7 tham số)
CREATE PROCEDURE SP_THEM_KHACH_HANG(
    IN p_TENDOITAC NVARCHAR(255),
    IN p_SODIENTHOAI NVARCHAR(255),
    IN p_DIACHI NVARCHAR(255),
    IN p_EMAIL NVARCHAR(255),
    IN p_LOAIDOITAC NVARCHAR(255),
    IN p_DIEMTICHLUY INT,
    IN p_NGAYTHAMGIA DATE
)
BEGIN
    DECLARE v_EXIST_ID INT DEFAULT NULL;
    DECLARE v_EXIST_LOAI NVARCHAR(255);
    DECLARE v_LOAI NVARCHAR(255) DEFAULT IFNULL(p_LOAIDOITAC, 'KHACH_HANG');
    
    -- Kiểm tra trùng SĐT
    SELECT MADOITAC, LOAIDOITAC INTO v_EXIST_ID, v_EXIST_LOAI
    FROM DOI_TAC WHERE SODIENTHOAI = p_SODIENTHOAI LIMIT 1;

    START TRANSACTION;
    BEGIN
        DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

        IF v_EXIST_ID IS NOT NULL THEN
            IF v_EXIST_LOAI IN ('KHACH_HANG', 'CA_HAI') THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Khách hàng với số điện thoại này đã tồn tại';
            END IF;
            -- Nâng cấp Nhà cung cấp thành Cả hai hoặc loại mới
            UPDATE DOI_TAC SET LOAIDOITAC = v_LOAI, TENDOITAC = p_TENDOITAC, DIACHI = p_DIACHI, EMAIL = NULLIF(TRIM(p_EMAIL), '') WHERE MADOITAC = v_EXIST_ID;
            INSERT INTO KHACH_HANG(MADOITAC, DIEMTICHLUY, NGAYTHAMGIA) VALUES(v_EXIST_ID, IFNULL(p_DIEMTICHLUY, 0), IFNULL(p_NGAYTHAMGIA, CURDATE()));
        ELSE
            -- Tạo mới
            INSERT INTO DOI_TAC(TENDOITAC, SODIENTHOAI, DIACHI, EMAIL, LOAIDOITAC)
            VALUES(p_TENDOITAC, p_SODIENTHOAI, p_DIACHI, NULLIF(TRIM(p_EMAIL), ''), v_LOAI);
            SET v_EXIST_ID = LAST_INSERT_ID();
            INSERT INTO KHACH_HANG(MADOITAC, DIEMTICHLUY, NGAYTHAMGIA) VALUES(v_EXIST_ID, IFNULL(p_DIEMTICHLUY, 0), IFNULL(p_NGAYTHAMGIA, CURDATE()));
        END IF;
        COMMIT;
    END;
END $$

-- Sửa khách hàng (8 tham số)
CREATE PROCEDURE SP_SUA_KHACH_HANG(
    IN p_MADOITAC INT,
    IN p_TENDOITAC NVARCHAR(255),
    IN p_SODIENTHOAI NVARCHAR(255),
    IN p_DIACHI NVARCHAR(255),
    IN p_EMAIL NVARCHAR(255),
    IN p_LOAIDOITAC NVARCHAR(255),
    IN p_DIEMTICHLUY INT,
    IN p_NGAYTHAMGIA DATE
)
BEGIN
    START TRANSACTION;
    BEGIN
        DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
        
        UPDATE DOI_TAC 
        SET TENDOITAC = p_TENDOITAC, 
            SODIENTHOAI = p_SODIENTHOAI, 
            DIACHI = p_DIACHI, 
            EMAIL = NULLIF(TRIM(p_EMAIL), ''),
            LOAIDOITAC = p_LOAIDOITAC
        WHERE MADOITAC = p_MADOITAC;

        UPDATE KHACH_HANG
        SET DIEMTICHLUY = p_DIEMTICHLUY, NGAYTHAMGIA = p_NGAYTHAMGIA
        WHERE MADOITAC = p_MADOITAC;
        
        COMMIT;
    END;
END $$

CREATE PROCEDURE SP_XOA_KHACH_HANG(IN p_MADOITAC INT)
BEGIN
    START TRANSACTION;
    BEGIN
        DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
        DELETE FROM KHACH_HANG WHERE MADOITAC = p_MADOITAC;
        IF (SELECT LOAIDOITAC FROM DOI_TAC WHERE MADOITAC = p_MADOITAC) = 'CA_HAI' THEN
            UPDATE DOI_TAC SET LOAIDOITAC = 'NHA_CUNG_CAP' WHERE MADOITAC = p_MADOITAC;
        ELSE
            DELETE FROM DOI_TAC WHERE MADOITAC = p_MADOITAC;
        END IF;
        COMMIT;
    END;
END $$

CREATE PROCEDURE SP_LAY_DANH_SACH_KHACH_HANG()
BEGIN
    SELECT D.MADOITAC, D.TENDOITAC, D.SODIENTHOAI, D.EMAIL, D.DIACHI, D.LOAIDOITAC, K.DIEMTICHLUY, K.NGAYTHAMGIA, K.LOAIKHACHHANG
    FROM DOI_TAC D JOIN KHACH_HANG K ON D.MADOITAC = K.MADOITAC
    ORDER BY D.MADOITAC DESC;
END $$

CREATE PROCEDURE SP_TIM_KIEM_KHACH_HANG(IN p_KEYWORD NVARCHAR(255))
BEGIN
    SET @pattern = CONCAT('%', IFNULL(p_KEYWORD, ''), '%');
    SELECT D.MADOITAC, D.TENDOITAC, D.SODIENTHOAI, D.EMAIL, D.DIACHI, D.LOAIDOITAC, K.DIEMTICHLUY, K.NGAYTHAMGIA, K.LOAIKHACHHANG
    FROM DOI_TAC D JOIN KHACH_HANG K ON D.MADOITAC = K.MADOITAC
    WHERE D.TENDOITAC LIKE @pattern OR D.SODIENTHOAI LIKE @pattern OR D.EMAIL LIKE @pattern
    ORDER BY D.MADOITAC DESC;
END $$

-- ==========================================
-- 4. TRIGGERS
-- ==========================================

-- Trigger kiểm tra tính hợp lệ của DOI_TAC
CREATE TRIGGER TRG_DOITAC_CHECK_KHACHHANG
BEFORE INSERT ON DOI_TAC FOR EACH ROW
BEGIN
    IF NEW.LOAIDOITAC IN ('KHACH_HANG', 'CA_HAI') THEN
        IF NEW.TENDOITAC IS NULL OR TRIM(NEW.TENDOITAC) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Tên không được rỗng'; END IF;
        IF NEW.SODIENTHOAI IS NULL OR NOT (NEW.SODIENTHOAI REGEXP '^[0-9]{10,11}$') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'SĐT không hợp lệ'; END IF;
    END IF;
END $$

-- Trigger tự động nâng hạng khi thay đổi điểm (Áp dụng cả khi Admin sửa điểm)
CREATE TRIGGER TRG_CAPNHAT_LOAI_KHACH
BEFORE UPDATE ON KHACH_HANG FOR EACH ROW
BEGIN
    IF NEW.DIEMTICHLUY < 1000 THEN SET NEW.LOAIKHACHHANG = 'Đồng';
    ELSEIF NEW.DIEMTICHLUY < 5000 THEN SET NEW.LOAIKHACHHANG = 'Bạc';
    ELSE SET NEW.LOAIKHACHHANG = 'Vàng';
    END IF;
END $$

-- Trigger tự động set hạng khi Insert
CREATE TRIGGER TRG_KHACHHANG_RANK_INSERT
BEFORE INSERT ON KHACH_HANG FOR EACH ROW
BEGIN
    IF NEW.DIEMTICHLUY < 1000 THEN SET NEW.LOAIKHACHHANG = 'Đồng';
    ELSEIF NEW.DIEMTICHLUY < 5000 THEN SET NEW.LOAIKHACHHANG = 'Bạc';
    ELSE SET NEW.LOAIKHACHHANG = 'Vàng';
    END IF;
END $$

-- Trigger tích điểm khi có hóa đơn
CREATE TRIGGER TRG_HOADON_TICH_DIEM
AFTER INSERT ON HOA_DON_BAN_HANG FOR EACH ROW
BEGIN
    UPDATE KHACH_HANG SET DIEMTICHLUY = DIEMTICHLUY + NEW.DIEMTICHDUOC - NEW.DIEMSUDUNG WHERE MADOITAC = NEW.MADOITAC;
END $$

DELIMITER ;
